package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.User;
import hello.UserRepository;
import hello.Book;
import hello.BookRepository;

import java.util.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	@Autowired
	private BookRepository bookRepository;

	//Invoke upon "Sign Up", return JSON String
    //Input: username, password
    //Output: If success, new User class in JSON. If fail, empty User class in JSON
    //FAIL CASE: The new User's username already existed in the database
	@GetMapping(path="/addUser")
	public @ResponseBody String addNewUser (@RequestParam String username
			, @RequestParam String password, @RequestParam double longitude
			, @RequestParam double latitude) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		User userToAdd = new User();
		userToAdd.setUsername(username);
		userToAdd.setPassword(password);
		userRepository.save(userToAdd);
		return "Saved new user: " + username + "\n";
	}
	
	@GetMapping(path="/addBook") 
	public @ResponseBody String addNewBook (@RequestParam int ownerID
			, @RequestParam String author, @RequestParam int rating, @RequestParam String title
			, @RequestParam String picture, @RequestParam double longitude, @RequestParam double latitude) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
// 		Book bookToAdd = new Book(bookID, ownerID, author, rating, title, picture, longitude, latitude);
		Book bookToAdd = new Book();
		bookToAdd.setOwnerID(ownerID);
		bookToAdd.setAuthor(author);
		bookToAdd.setRating(rating);
		bookToAdd.setTitle(title);
		bookToAdd.setPicture(picture);
		bookToAdd.setLongitude(longitude);
		bookToAdd.setLatitude(latitude);
		bookRepository.save(bookToAdd);
		return "Saved new book: " + title + "\n";
	}

	@GetMapping(path="/allUsers")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
	@GetMapping(path="/allBooks")
	public @ResponseBody Iterable<Book> getAllBooks() {
		
		return bookRepository.findAll() == null ? null : bookRepository.findAll();
	}
	
	@GetMapping(path="/getUser")
	public @ResponseBody User getUser(@RequestParam String username, @RequestParam String password) {
		return userRepository.findByUsernameAndPassword(username, password);
	}
	
	//Invoke upon "Login", return a jsonfied user class if success		
		//Input: username, password
		//Output: If Success, return the whole User class in JSON. If fail, return empty User class in JSON
		//FAIL CASE: username doesn't exist OR password doesn't match with the username.
	@GetMapping(path="/verifyUser")
	public @ResponseBody User verifyUser(@RequestParam String username, @RequestParam String password
		, @RequestParam double longitude, @RequestParam double latitude) {
		User userToVerify = userRepository.findByUsernameAndPassword(username, password);
		if(userToVerify != null) {
			userToVerify.setLongitude(longitude);
			userToVerify.setLatitude(latitude);
			userRepository.save(userToVerify);
		}
		return userToVerify;
	}
	
	//TODO: update user location simply by user Id
	
	@GetMapping(path="/updateUserBookLocations")
	public @ResponseBody String updateUserBookLocations(@RequestParam int userID
	, @RequestParam double longitude, @RequestParam double latitude) {
		Iterable<Book> userBooksIterable = bookRepository.findByOwnerID(userID);
		
		List<Book> userBooks = new ArrayList<Book>();
		userBooksIterable.forEach(userBooks::add);
		
		for(Book book : userBooks) {
			if(book.getOwnerID() == userID) {
				book.setLatitude(latitude);
				book.setLongitude(longitude);
				bookRepository.save(book);
			}
		}
		if(userBooks.size() > 0) {
			return userBooks.size() + " book(s) updated for userID: " + userID + "\n";
		}
		else {
			return "No books found for specified user ID\n";
		}

	}
	
	//Invoke upon "Search Users", return a jsonfied user list for front end.
	//Input: the Name typed by the user.
	//Output: If success, return all the users in JSON. If fail, return empty user list in JSON		
	//FAIL CASE: No instances of such a Name in userTable.
	// return and test (currently create user does not add a name field)
	@GetMapping(path="/searchUsers")
	public @ResponseBody Iterable<User> searchUsers(@RequestParam String name) {
		return userRepository.findByName(name);
	}
	
	@GetMapping(path="/updateUser")
	public @ResponseBody String updateUser(@RequestParam int userID, @RequestParam String password
		, @RequestParam String name, @RequestParam String picture) {
		User userToUpdate = userRepository.findByUserID(userID);
		if(userToUpdate == null) {
			return "User: " + userID + " not found \n";
		}
		if(userToUpdate.getPassword().equals(password)) {
			userToUpdate.setName(name);
			userToUpdate.setPicture(picture);
			userRepository.save(userToUpdate);
			return "User: " + userID + " updated \n";
		}
		else {
			return "Invalid password for user: " + userID + "\n";
		}
	}
	
	@GetMapping(path="/getUserBookList")
	public @ResponseBody Iterable<Book> getUserBookList(@RequestParam int ownerID) {
		return bookRepository.findByOwnerID(ownerID);
	}
	

	private static double getDistance(double lat1, double lon1, double lat2, double lon2, String unit) {
		double theta = lon1 - lon2;
		double dist = Math.sin(deg2rad(lat1)) * Math.sin(deg2rad(lat2)) + Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * Math.cos(deg2rad(theta));
		dist = Math.acos(dist);
		dist = rad2deg(dist);
		dist = dist * 60 * 1.1515;
		if (unit == "K") {
			dist = dist * 1.609344;
		 } 
		else if (unit == "N") {
			dist = dist * 0.8684;
		}
		return (dist);
	}
	/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
	/*::  This function converts decimal degrees to radians             :*/
	/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
	private static double deg2rad(double deg) {
		return (deg * Math.PI / 180.0);
	}
	/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
	/*::  This function converts radians to decimal degrees             :*/
	/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
	private static double rad2deg(double rad) {
		return (rad * 180.0 / Math.PI);
	}
	
}